module Foxtrot
  
  # Definitions from libsmbclient.h
  SMBC_BASE_FD = 10000
  
  SMBC_WORKGROUP = 1
  SMBC_SERVER = 2
  SMBC_FILE_SHARE = 3
  SMBC_PRINTER_SHARE = 4
  SMBC_COMMS_SHARE = 5
  SMBC_IPC_SHARE = 6
  SMBC_DIR = 7
  SMBC_FILE = 8
  SMBC_LINK = 9
  
  DOS_MODE_READONLY = 0x01
  DOS_MODE_HIDDEN = 0x02
  DOS_MODE_SYSTEM = 0x04
  DOS_MODE_VOLUME_ID = 0x08
  DOS_MODE_DIRECTORY = 0x10
  DOS_MODE_ARCHIVE = 0x20
  
  
  
  
end